const portfolioData = [
  {
    name: "Todo App",
    type: "frontend",
    live: "https://notesomething.netlify.app/",
    code: "",
    image: "portfolioimages/todo.png",
  },
  {
    name: "Country Search",
    type: "frontend",
    live: "https://searchccountry.netlify.app/",
    code: "",
    image: "portfolioimages/countryapp.png",
  },
  {
    name: "Admin Deahboard",
    type: "frontend",
    live: "https://dashboard-web2023.netlify.app/",
    code: "",
    image: "portfolioimages/dashboard.png",
  },
  {
    name: "Gym",
    type: "frontend",
    live: "https://gym-web-2023.netlify.app/",
    code: "",
    image: "portfolioimages/gym.png",
  },

  {
    name: "Store Api",
    type: "backend",
    live: "",
    code: "https://github.com/Talalmahmud/node-js-project/tree/main/store-api",
    image: "portfolioimages/backend.png",
  },
  {
    name: "Task Manager",
    type: "backend",
    live: "",
    code: "https://github.com/Talalmahmud/node-js-project/tree/main/task-manager",
    image: "portfolioimages/backend.png",
  },
  {
    name: "E-commerce",
    type: "backend",
    live: "https://dashboard-rho-sandy.vercel.app/",
    code: "https://github.com/Talalmahmud/ecommerce.git",
    image: "portfolioimages/ecommerce.webp",
  },
  {
    name: "Social Media",
    type: "frontend",
    live: "https://social-media-2023.netlify.app/",
    code: "",
    image: "portfolioimages/socialmedia.png",
  },
  {
    name: "Netflix Clone",
    type: "frontend",
    live: "https://next-ntflix-clone.vercel.app/",
    code: "",
    image: "portfolioimages/socialmedia.png",
    code: "https://github.com/Talalmahmud/ecommerce.git",
  },
  //   {
  //     name: "Chat Api",
  //     type: "mern",
  //     live: "",
  //     code: "",
  //     image: "../../../assets/chatapp.jpg",
  //   },
];
export default portfolioData;
